name: CI
on: [push, pull_request]

# cancel older workflow runs
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  aarch64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
        submodules: recursive
    - run: sudo gem install apt-spy2 && sudo apt-spy2 fix
    - run: sudo apt-get update -y
    - run: sudo apt-get install -o Acquire::Retries=5 -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu qemu-user-static
    - run: cmake -DCMAKE_TOOLCHAIN_FILE=CMakeARM64Cross.txt
    - run: make -j4 VERBOSE=1
    - run: make -j4 test ARGS=-V
  macOS:
    name: macOS
    runs-on: macOS-latest
    steps:
    #- name: init
    #  run: brew install automake
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
        submodules: true
    - run: CXXFLAGS='-std=c++17' cmake .
    - run: make -j4 VERBOSE=1
    - run: make -j4 test ARGS=-V